# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f8273b3a11c12ccf79d069769b6c2674ce8d9fcee2ccd803545fba452c9e87202e042ef4eb9f8ae7e5b94ffdfe782b482e351cdac2424d22842a7bedcf765eb

test:
  secret_key_base: 1697c8aaae4c6672749cc94e7b5d651694e83ae00d26687112980bc9f958ba8731fb623d3fdcd546e54a5f7b081bbf17b61507caa61462d8ce7d1e494f8ffcbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
