octopus:
  environments:
    - development
    - production
    - test
  development:
    admin:
      adapter: postgresql
      encoding: unicode
      database: najacloud_admin_development
      pool: 5
      host: localhost
      port: 5432
    log:
      adapter: postgresql
      encoding: unicode
      database: najacloud_log_development
      pool: 5
      host: localhost
      port: 5432
  test:
    admin:
      adapter: postgresql
      encoding: unicode
      database: najacloud_admin_test
      pool: 5
      host: localhost
      port: 5432
    log:
      adapter: postgresql
      encoding: unicode
      database: najacloud_log_test
      pool: 5
      host: localhost
      port: 5432
  production:
    admin:
      adapter: postgresql
      encoding: unicode
      database: najacloud_admin_production
      pool: 5
      host: localhost
      port: 5432
